# Generated by Django 4.1.2 on 2023-05-14 04:15

# Generated by Django 4.1.2 on 2023-05-11 15:02
from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from datetime import datetime, timedelta
import time

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    email='shop-enu140523@mail.ru',
    password='SsNn5678+-@', 
    last_login=datetime.now())
    print("Суперпользователь создан")
    
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id2
    user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Менеджер', last_name='', last_login=datetime.now())
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    # Простые пользователи (заявители) id3-27
    user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Дина', last_name='Мусина', last_login=datetime.now())
    user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Адия', last_name='Жунусова', last_login=datetime.now())
    user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айнура', last_name='Кенина', last_login=datetime.now())
    user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Рустем', last_name='Какимов', last_login=datetime.now())
    user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Алишер', last_name='Кабдуалиев', last_login=datetime.now())
    user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Бауржан', last_name='Арыкбаев', last_login=datetime.now())
    user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Алишер', last_name='Танатаров', last_login=datetime.now())
    user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Мерует', last_name='Искакова', last_login=datetime.now())
    user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Ольга', last_name='Муравьева', last_login=datetime.now())
    user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Ақжарқын', last_name='Сансызбаева', last_login=datetime.now())
    user = User.objects.create_user(username='user11', password='Uu0066+-', email='user11@mail.ru', first_name='Арайлым', last_name='Алматова', last_login=datetime.now())
    user = User.objects.create_user(username='user12', password='Uu0066+-', email='user12@mail.ru', first_name='Айгерім', last_name='Дүйсенбиева', last_login=datetime.now())
    user = User.objects.create_user(username='user13', password='Uu0066+-', email='user13@mail.ru', first_name='Салтанат', last_name='Зиноллаева', last_login=datetime.now())
    user = User.objects.create_user(username='user14', password='Uu0066+-', email='user14@mail.ru', first_name='Сейтқасым', last_name='Болат', last_login=datetime.now())
    user = User.objects.create_user(username='user15', password='Uu0066+-', email='user15@mail.ru', first_name='Сара', last_name='Фазилова', last_login=datetime.now())
    user = User.objects.create_user(username='user16', password='Uu0066+-', email='user16@mail.ru', first_name='Бектас', last_name='Ерсейіт', last_login=datetime.now())
    user = User.objects.create_user(username='user17', password='Uu0066+-', email='user17@mail.ru', first_name='Диас', last_name='Мырзаш', last_login=datetime.now())
    user = User.objects.create_user(username='user18', password='Uu0066+-', email='user18@mail.ru', first_name='Нұржан', last_name='Жүрсінбек', last_login=datetime.now())
    user = User.objects.create_user(username='user19', password='Uu0066+-', email='user19@mail.ru', first_name='Дина', last_name='Жағыпар', last_login=datetime.now())
    user = User.objects.create_user(username='user20', password='Uu0066+-', email='user20@mail.ru', first_name='Жастілек', last_name='Жасталап', last_login=datetime.now())
    user = User.objects.create_user(username='user21', password='Uu0066+-', email='user21@mail.ru', first_name='Еркебұлан', last_name='Қадыхан', last_login=datetime.now())
    user = User.objects.create_user(username='user22', password='Uu0066+-', email='user22@mail.ru', first_name='Молдир', last_name='Бутабекова', last_login=datetime.now())
    user = User.objects.create_user(username='user23', password='Uu0066+-', email='user23@mail.ru', first_name='Аружан', last_name='Таурбекова', last_login=datetime.now())
    user = User.objects.create_user(username='user24', password='Uu0066+-', email='user24@mail.ru', first_name='Алтынай', last_name='Қожанова', last_login=datetime.now())
    user = User.objects.create_user(username='user25', password='Uu0066+-', email='user25@mail.ru', first_name='Эльнара', last_name='Иминова', last_login=datetime.now())
    print("Созданы простые пользователи")

    ##### Каталог товаров + Продажа + Доставка #####

    Category = apps.get_model("product", "Category")
    Catalog = apps.get_model("product", "Catalog")
    Sale = apps.get_model("product", "Sale")
    Delivery = apps.get_model("product", "Delivery")

    #################### -------------------- ####################

    category = Category()
    category.title='Смартфон'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Tecno POP 5, 32Gb, Ice Lake Green (BD2p)'
    catalog.details='Смартфон POP 5 оснащен классическим экраном 6.1" HD+ с выемкой в виде точки для более широкого обзора и удобства просмотра. Экран смартфона POP 5 также обладает сверхвысоким разрешением (720x1560), что обеспечивает более четкое и впечатляющее изображение.'
    catalog.price=38990
    catalog.photo='images/product1.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 3
    sale.rating = 5
    sale.details='Достоинства: тонкий и легкий большой экран'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####

    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 4
    sale.rating = 4
    sale.details='Достоинства:Довольно не плохой. Недостатки:Простоват, экономия на ,,шпильках,,'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Tecno POP 4 Pro, 16Gb, Cosmic Shine (BC3)'
    catalog.details='В телефоне POP 4 Pro используется классический экран с каплевидным вырезом диагональю 6.52 дюйма. Большой размер дисплея и идеальное соотношение размеров экрана и корпуса позволяют достичь лучшего качества отображения.'
    catalog.price=39990
    catalog.photo='images/product2.jpg'
    catalog.save()
    
    #sale = Sale()
    ##sale.saleday = datetime.now()
    #sale.catalog = catalog
    #sale.price = catalog.price
    #sale.quantity = 1
    #sale.user_id = 4
    #sale.rating = 5
    #sale.details='Отзыв'
    #sale.save()
    #sale.saleday = datetime.now() - timedelta(days=29)
    #sale.save()

    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday 
    #delivery.movement = 'Заявка принята в обработку'
    #delivery.details='Заявка принята в обработку'
    #delivery.save()
    #delivery.deliveryday = sale.saleday
    #delivery.save()
    
    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday
    #delivery.movement = 'Заказ в пути'
    #delivery.details='Заказ в пути'
    #delivery.save()
    #delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    #delivery.save()
    
    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday
    #delivery.movement = 'Заявка закрыта, заказ доставлен'
    #delivery.details='Заявка закрыта, заказ доставлен'
    #delivery.save()
    #delivery.deliveryday = sale.saleday + timedelta(hours=1)
    #delivery.save()

    ###### ----- ######
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Tecno Spark 6, 64Gb, Comet Black (KE7)'
    catalog.details='Вычислительная мощность центрального процессора увеличилась на 60%, производительность графического процессора увеличилась на 26%. Мощный процессор обеспечивает стабильную и плавную работу устройства, о которой вы даже не догадывались, и гарантирует, что игры станут еще одним невероятным удовольствием.'
    catalog.price=64990
    catalog.photo='images/product3.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 5
    sale.rating = 5
    sale.details='Просто отличный телефон за эти деньги!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Tecno POP 2F, 16Gb, Midnight Black (B1f)'
    catalog.details='Благодаря 16 ГБ памяти у вас будет больше места для хранения ваших любимых и драгоценных воспоминаний. Расширение хранилища - отличный шаг к достижению высочайшей производительности, предлагая потрясающий пользовательский интерфейс'
    catalog.price=27990
    catalog.photo='images/product4.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 6
    sale.rating = 5
    sale.details='Цена=качество. отличный телефон за низкую стоимость. В комплекте прозрачный чехол. всё устроило.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ------ ######
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Tecno POP 3, 16Gb, Sandstone Black (BB2)'
    catalog.details='Благодаря 16 ГБ ПЗУ у вас будет больше места для хранения ваших любимых воспоминаний и важных файлов. Меньше беспокойства о частой уборке, чтобы освободить место. Практичный и как всегда отличный.'
    catalog.price=28990
    catalog.photo='images/product5.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 7
    sale.rating = 4
    sale.details='Шустро работает. Фото яркие, не виснет.Недостатки:В самом телефоне от производителя сделаны недостатки. Разработчики телефона посчитали что пять сообщений в день (даже не в сутки) будет в полне достаточно. В следующий раз оповещения начнут работать только через сутки. И за это время хоть башкой бейся но если пять оповещений было, то даже важные оповещения не дойдут'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Samsung Galaxy A03 Core, 32Gb, Black (SM-A032F)'
    catalog.details='Расширьте границы доступного с 6.5-дюймовым экраном с V-образным вырезом. Благодаря технологии HD+ дисплей Galaxy A03 Core демонстрирует яркую, четкую и чистую картинку.'
    catalog.price=48990
    catalog.photo='images/product6.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 8
    sale.rating = 5
    sale.details='Хороший телефон, для ребенка самое то, игры тянет нормально, не глючит, зарядку держит достойно, камера, конечно, слабенькая, но за эти деньги другого и не приходится ожидать.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####

    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 9
    sale.rating = 4
    sale.details='Достоинства: Заряд батарейки, особенно первое время, держит намного больше чем известный яблочный бренд). Недостатки: Сенсор экрана настолько близок к краю смартфона, что привычно держать его в одной руке и манипулировать пальцем другой проблематично.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Samsung Galaxy A22, 64Gb, White (SM-A225F)'
    catalog.details='Насладитесь детальным изображением на Super AMOLED 6.4'' Infinity-U экране с разрешением HD+ и яркостью до 600 нит. Благодаря увеличенному экрану вы увидите больше, а сверх плавная прокрутка обеспечивает комфортный просмотр во время игрового сеанса или скроллинга изображения на экране'
    catalog.price=90100
    catalog.photo='images/product7.jpg'
    catalog.save()
    
    #sale = Sale()
    ##sale.saleday = datetime.now() 
    #sale.catalog = catalog
    #sale.price = catalog.price
    #sale.quantity = 1
    #sale.user_id = 9
    #sale.rating = 5
    #sale.details='Отзыв!!'
    #sale.save()
    #sale.saleday = datetime.now() - timedelta(days=30)
    #sale.save()

    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday 
    #delivery.movement = 'Заявка принята в обработку'
    #delivery.details='Заявка принята в обработку'
    #delivery.save()
    #delivery.deliveryday = sale.saleday
    #delivery.save()
    
    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday
    #delivery.movement = 'Заказ в пути'
    #delivery.details='Заказ в пути'
    #delivery.save()
    #delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    #delivery.save()
    
    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday
    #delivery.movement = 'Заявка закрыта, заказ доставлен'
    #delivery.details='Заявка закрыта, заказ доставлен'
    #delivery.save()
    #delivery.deliveryday = sale.saleday + timedelta(hours=1)
    #delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Samsung Galaxy A02, 32Gb, Black (SM-A022G)'
    catalog.details='Большой 6.5-дюймовый HD+ экран с V-образным вырезом для камеры создан для и полного погружения в контент.'
    catalog.price=53990
    catalog.photo='images/product8.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 10
    sale.rating = 5
    sale.details='Для своих ттх довольно шустрый , экран в паре с батареей выдают отличную автономность , если сравнивать с редми 9 3/32 то данный аппарат намного комфортнее , без фризов ,тротлинга'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Samsung Galaxy A12, 32Gb, Blue (SM-A127F)'
    catalog.details='Большой 6.5-дюймовый HD+ экран с V-образным вырезом для камеры создан для полного погружения в контент. Благодаря поддержке технологии HD+ картинка на Galaxy A12 яркая и насыщенная.'
    catalog.price=69990
    catalog.photo='images/product9.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 11
    sale.rating = 5
    sale.details='Отличный экран, обалденная камера, долго держит зарядку, сканер отпечатка пальца в кнопке включения, разблокировка по лицу, суперский внешний вид!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Samsung Galaxy A32, 64Gb, Awesome Black (SM-A325F)'
    catalog.details='Насладитесь детальным изображением на Super AMOLED 6.4'' Infinity-U экране с разрешением FHD+ и яркостью до 800 нит, которое отлично видно даже при ярком дневном свете. Функция защиты глаз "Eye Comfort Shield" снижает уровень синего свечения, а сверх плавная прокрутка обеспечивает комфортный просмотр во время игрового сеанса или скроллинга изображения на экране.'
    catalog.price=199990
    catalog.photo='images/product10.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 12
    sale.rating = 5
    sale.details='Экран, камеры, аккумулятор, шустрая память, сканер под стеклом, тройной слот (2sim+MicroSD), относительно невысокая цена, ловля сигнала всяких GPS (к обычным + байду и галилео), wifi многодиапазонный, NFC и 4G. Красивый дизайн и красивый небесный цвет.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Xiaomi Redmi 9C, 128Gb, Midnight Gray (M2006C3MG)'
    catalog.details='Размер экрана, дюйм: 6.52 / Разрешение экрана: 1600 х 720 [20:9] / Тип матрицы: IPS / Объем оперативной памяти: 4 Гб / Объем встроенной памяти: 64 Гб / Модель процессора: Snapdragon 460 / Частота процессора: 1.8 ГГц / Разрешение основной камеры: 13 Мп + 2 Мп + 2 Мп / Разрешение фронтальной камеры: 8 Мп / Беспроводные интерфейсы: Wi-Fi; Bluetooth / Емкость аккумулятора: 5000 мАч'
    catalog.price=69900
    catalog.photo='images/product11.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 13
    sale.rating = 5
    sale.details='Достоинства:Обалденный телефон, качественный!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####

    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 14
    sale.rating = 4
    sale.details='Достоинства:Не плохой аппарат за свои деньги. Недостатки:Немного греется при зарядке.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Xiaomi Redmi 9A, 32Gb, Granite Grey (M2006C3LG)'
    catalog.details='Xiaomi Redmi 9A - версия бюджетного смартфона, главными особенностями которого являются большой экран с диагональю 6.53" и емкий аккумулятор на 5000 мАч. Основная и фронтальная AI камеры (13 Мп и 5 Мп соответственно) позволяют без труда делать прекрасные качественные фотографии.'
    catalog.price=54990
    catalog.photo='images/product12.jpg'
    catalog.save()
    
    #sale = Sale()
    ##sale.saleday = datetime.now()
    #sale.catalog = catalog
    #sale.price = catalog.price
    #sale.quantity = 1
    #sale.user_id = 14
    #sale.rating = 5
    #sale.details='Отзыв'
    #sale.save()
    #sale.saleday = datetime.now() - timedelta(days=29)
    #sale.save()

    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday 
    #delivery.movement = 'Заявка принята в обработку'
    #delivery.details='Заявка принята в обработку'
    #delivery.save()
    #delivery.deliveryday = sale.saleday
    #delivery.save()
    
    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday
    #delivery.movement = 'Заказ в пути'
    #delivery.details='Заказ в пути'
    #delivery.save()
    #delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    #delivery.save()
    
    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday
    #delivery.movement = 'Заявка закрыта, заказ доставлен'
    #delivery.details='Заявка закрыта, заказ доставлен'
    #delivery.save()
    #delivery.deliveryday = sale.saleday + timedelta(hours=1)
    #delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Xiaomi Redmi Note 9S, 64Gb, Interstellar Grey'
    catalog.details='Таких камер у Xiaomi еще не было. Первым бросается в глаза именно квадратный блок камер. 4 камеры занимают небольшую площадь и гармонично смотрятся в общем дизайне устройства.'
    catalog.price=88900
    catalog.photo='images/product13.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 15
    sale.rating = 5
    sale.details='Соотношение цена-качество. Хорошая рабочая лошадка по адекватной цене. Брал жене на замену Xiaomi redmi note 3 pro. Жена довольна. Пользуется уже полгода, нареканий нет.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Xiaomi Redmi 10, 4Gb, 64Gb, Sea Blue (21061119AG)'
    catalog.details='Xiaomi Redmi 10 первый обладатель мощного процессора MediaTek Helio G88. Совершенно новый чип обеспечивает более четкие фотографии и улучшенный игровой процесс.'
    catalog.price=89990
    catalog.photo='images/product14.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 16
    sale.rating = 5
    sale.details='Неплохой экран. Плёнка на экране и силиконовый чехол в комплекте на первые дни пользования. Камера нормальная.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Xiaomi Redmi Note 11, 64Gb, Twilight Blue (2201117TG)'
    catalog.details='Размер экрана, дюйм: 6.43; Разрешение экрана: 2400 x 1080 [20:9]; Тип матрицы: AMOLED; Объем оперативной памяти: 4 Гб; Объем встроенной памяти: 64 Гб; Модель процессора: Snapdragon 680; Частота процессора: 2.4 ГГц + 1.9 ГГц; Основная камера, Мп: 50 + 8 + 2 + 2; Фронтальная камера, Мп: 13; Беспроводные интерфейсы: Wi-Fi, Bluetooth, IrDA; Емкость аккумулятора: 5000 мАч'
    catalog.price=109990
    catalog.photo='images/product15.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 17
    sale.rating = 5
    sale.details='Достоинства:цена мощность экран быстрая зарядка батарея'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон Meizu M10, 2Gb, 32Gb, Phantom Black (M918H)'
    catalog.details='Размер экрана, дюйм: 6.5 / Разрешение экрана: 1600 х 720 [20:9] / Объем оперативной памяти: 2 Гб / Объем встроенной памяти: 32 Гб / Модель процессора: Helio P25 / Частота процессора: 2.5 ГГц / Разрешение основной камеры: 13 Мп + 2 Мп + 2 Мп / Разрешение фронтальной камеры: 8 Мп / Беспроводные интерфейсы: Wi-Fi; Bluetooth / Емкость аккумулятора: 4000 мАч'
    catalog.price=45900
    catalog.photo='images/product16.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 18
    sale.rating = 4
    sale.details='Достоинства:Хороший дизайн, цена. Недостатки:Ошибки при работе с приложениями'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ###### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон OPPO A54, 64Gb, Black (CPH2239)'
    catalog.details='3D-корпус с уникальным дизайном задней крышки и тонкой рамкой 0.2 мм не только изящно выглядит, но и удобен при долгом использовании.'
    catalog.price=94900
    catalog.photo='images/product17.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 19
    sale.rating = 5
    sale.details='Шустрый, неплохая камера за эти деньги, удачный интерфейс и неплохой экран, довольно долго работает без зарядки при повышенном уровне использования.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон OPPO A74, 128Gb, Black (CPH2219)'
    catalog.details='Продвинутый сканер, встроенный в экран устройства, быстро и с высокой точностью считывает отпечатки пальцев и позволяет разблокировать смартфон одним касанием.'
    catalog.price=119990
    catalog.photo='images/product18.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 20
    sale.rating = 5
    sale.details='Сочетание, цены, комплектации железа. Ну и софта. Всё работает хорошо для цены бюджетного телефона.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ###### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон OPPO Reno4 Lite, 8Gb, Black (CPH2125)'
    catalog.details='Смартфоны серии Reno являются самыми тонкими и легкими в модельном ряду OPPO, корпус таких устройств имеет гладко закругленные края, им очень удобно пользоваться.'
    catalog.price=125990
    catalog.photo='images/product19.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 21
    sale.rating = 5
    sale.details='Просто OPPO. У меня наушники, усилитель, беспроводная гарнитура всё OPPO. И что важно 8Гб+128Гб+слот для флэш карт.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смартфон OPPO Reno5 Lite, 128Gb, Black (CPH2205)'
    catalog.details='Камера Reno5 Lite с четырьмя объективами и искусственным интеллектом идеально подходит для съемки всех моментов жизни. Reno5 Lite отображает жизненный путь в ярких и кристально чистых деталях - от макросъемки до сверхширокоугольных и зум-снимков.'
    catalog.price=139990
    catalog.photo='images/product20.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 22
    sale.rating = 5
    sale.details='Достоинства:Буквально всё, камера, память, операционка Coloros,много настроек персонализации, габариты телефона , очень легкий и тонкий, среди засилья лопатофонов выглядит элегантно.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Кнопочный телефон'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Мобильный телефон Nokia 125 DS, Black'
    catalog.details='Размер экрана, дюйм: 2.4 / Разрешение экрана: 240 x 320 / Объем встроенной памяти: 4 Мб / Емкость аккумулятора: 1020 мАч'
    catalog.price=13390
    catalog.photo='images/product21.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 23
    sale.rating = 5
    sale.details='Достоинства:огромные кнопки. тел отлично подошел владелице 83 лет. довольна.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####

    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 24
    sale.rating = 4
    sale.details='Достоинства:добротный,большой экран. Недостатки:тихий,мало мелодий на звонок'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Мобильный телефон Tecno T454, Champagne Gold'
    catalog.details='Размер экрана, дюйм: 2.8 / Разрешение экрана: 240 x 320 / Объем оперативной памяти: 4 Мб / Объем встроенной памяти: 4 Мб / Беспроводные интерфейсы: Bluetooth / Емкость аккумулятора: 1500 мАч'
    catalog.price=7990
    catalog.photo='images/product22.jpg'
    catalog.save()
    
    #sale = Sale()
    ##sale.saleday = datetime.now()
    #sale.catalog = catalog
    #sale.price = catalog.price
    #sale.quantity = 1
    #sale.user_id = 24
    #sale.rating = 5
    #sale.details='Отзыв'
    #sale.save()
    #sale.saleday = datetime.now() - timedelta(days=29)
    #sale.save()

    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday 
    #delivery.movement = 'Заявка принята в обработку'
    #delivery.details='Заявка принята в обработку'
    #delivery.save()
    #delivery.deliveryday = sale.saleday
    #delivery.save()
    
    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday
    #delivery.movement = 'Заказ в пути'
    #delivery.details='Заказ в пути'
    #delivery.save()
    #delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    #delivery.save()
    
    #delivery = Delivery()
    #delivery.sale = sale
    ##delivery.deliveryday = sale.saleday
    #delivery.movement = 'Заявка закрыта, заказ доставлен'
    #delivery.details='Заявка закрыта, заказ доставлен'
    #delivery.save()
    #delivery.deliveryday = sale.saleday + timedelta(hours=1)
    #delivery.save()

    ##### ----- #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Мобильный телефон TeXet TM-122, Black'
    catalog.details='TM-122 – не простой телефон, функции которого ограничиваются звонками и SMS. FM-радио, встроенный плеер и многое другое расширяют спектр применения мобильного устройства и позволяют полноценно реализовать его потенциал при максимуме комфорта.'
    catalog.price=4590
    catalog.photo='images/product23.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 25
    sale.rating = 4
    sale.details='Достоинства:Две симки;есть флэшка; привлекательный классический дизайн(корпус), Недостатки:Камеру я оценил на 3 с минусом.Или мне кажется,но такое ощущение что динамик не выдерживает громкости музыки,как будто то похрипывает,то нет,динамик могли и по качественней поставить'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Мобильный телефон Philips Xenium E109, Red'
    catalog.details='Если вам необходим опережающий моду дизайн для демонстрации вашего стиля, то эта плоская, современная конструкция с высококачественной отделкой не имеет себе равных.'
    catalog.price=8790
    catalog.photo='images/product24.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 26
    sale.rating = 5
    sale.details='Достоинства:Громкий, Долго держит заряд (недели полторы точно).'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    ##### ----- #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Мобильный телефон Prestigio Muze H1, Black'
    catalog.details='Компактный 2.4-дюймовый телефон с закругленными углами довольно приятно держать в руках. А благодаря небольшим габаритам и весу до 85 грамм он без труда поместится в карман джинсов или куртки. '
    catalog.price=6590
    catalog.photo='images/product25.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now()
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 27
    sale.rating = 5
    sale.details='Большой экран, большие клавиши, громкий звук. Удобная база, что легко поставит на заряд'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=29)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Смарт-часы'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смарт-часы Jet Kid Connect, Pink'
    catalog.details='Телефон, текстовые сообщения, голосовые сообщения, история перемещений, геолокация (только LBS), геозоны, кнопка SOS, удаленное фото, функция "Тихий звонок", будильник, встроенный фонарик, оповещение о разряде батареи, удаленный поиск часов (Anti lost)'
    catalog.price=8990
    catalog.photo='images/product26.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 4
    sale.rating = 5
    sale.details='Нормальный подарок для первоклассников'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смарт-часы Jet Kid Talk, Blue-Grey'
    catalog.details='Текстовые сообщения, голосовые сообщения, геолокация (только LBS), геозоны, история перемещений, кнопка SOS, удаленное фото, функция "Тихий звонок", будильник, встроенный фонарик, удаленный поиск часов'
    catalog.price=10990
    catalog.photo='images/product27.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 8
    sale.rating = 5
    sale.details='Дизайн, качество связи'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####

    catalog = Catalog()
    catalog.category = category
    catalog.title='Смарт-часы Jet Kid Friend, Pink-White'
    catalog.details='Стильные смарт-часы Jet Kid Friend выполняют не только свои главные функции в определении времени, по ним можно звонить, отправлять текстовые и голосовые сообщения и определять геолокацию. При этом есть возможность создавать безопасные для ребенка зоны, в которых ему разрешено находиться. Если же ребенок покинул одну из зон, то вы получите смс-уведомление на ваш смартфон.'
    catalog.price=14990
    catalog.photo='images/product28.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 12
    sale.rating = 4
    sale.details='Достоинства:Красивые. Недостатки:Геоалокация'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смарт-часы Canyon Marzipan CNS-SW75BL, Blue'
    catalog.details='Личный женский календарь позволит вам фиксировать и отслеживать всю нужную информацию с помощью смартфона и приложения Canyon Life в стильном, ультрапрочном аксессуаре с алюминиевым корпусом. Часы обладают внушительным набором различных датчиков и функций, упрощают управление камерой, позволяют отслеживать важные уведомления и мотивируют заниматься физической активностью.'
    catalog.price=16900
    catalog.photo='images/product29.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 16
    sale.rating = 4
    sale.details='Достоинства:Зарядку держит неделю. Недостатки:Неудобный ремешок, спать мне в них не удобно, поэтому сон я не считаю'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Смарт-часы Amazfit Neo A2001, Red'
    catalog.details='Часы Amazfit Neo оснащены четырехугольным экраном в стиле ретро с четырьмя физическими кнопками. Их конструкция обеспечивает идеальное соотношение стиля и универсальности. Это гармоничное сочетание классического дизайна и современных функций.'
    catalog.price=16990
    catalog.photo='images/product30.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 20
    sale.rating = 5
    sale.details='Отличные часы, заряд держат долго, четкая картинка, очень много функций! Доставка быстрая! Советую!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #################### -------------------- ####################

    category = Category()
    category.title='Планшет'   
    category.save()
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Планшет Prestigio MultiPad Wize 4117 3G, 8Gb, Wi-Fi+3G, Black'
    catalog.details='Wize 4117 3G – это 7.0-дюймовый 3G планшет на базе Android 8.1 Oreo. Удобный для решения повседневных задач благодаря соотношению качества изображения, функциональной начинки и дизайна корпуса.'
    catalog.price=25990
    catalog.photo='images/product31.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 3
    sale.rating = 5
    sale.details='Для просмотра видео, чтения книг, иногда Telegram и BK. Пользуюсь больше 2 месяцев, всё устраивает'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Планшет Prestigio Smartkids Max, 16Gb, Wi-Fi, Violet-Orange'
    catalog.details='Android 9.0 и 4-ядерный процессор для комфортной работы. Оцените все преимущества SmartKids Max с 4-ядерным процессором, 1 ГБ оперативной памяти и 16ГБ встроенной памяти. С такой начинкой все приложения и игры запускаются быстро. Доступ к популярным приложениям и играм, видеороликам, книгам, телешоу и образовательному контенту от iWawa гарантирован без подвисаний. Базируется планшет на операционной системе Android 9.0 Pie (Go edition) с простым и интуитивно понятным интерфейсом. Разобраться с функциями и фишками гаджета еще никогда не было так просто.'
    catalog.price=37500
    catalog.photo='images/product32.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 7
    sale.rating = 4
    sale.details='батарея не самая мощная что-то около 3х часов'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Планшет Lenovo Tab M8 (3rd Gen) TB-8506F, 32 GB, Wi-Fi, Iron Grey'
    catalog.details='Планшет Lenovo Tab M8 (3rd Gen) — ваш проводник в мир мультимедийных развлечений в формате HD. Времени автономной работы достаточно, чтобы вы могли часами наслаждаться любимыми видео без необходимости подзарядки, а благодаря сертификации TÜV существенно снижается зрительная нагрузка. Потрясающий 8-дюймовый TDDI-дисплей с матрицей IPS и узкими рамками обеспечивает превосходное качество изображения, а восьмиядерные процессоры, которыми теперь оснащается это устройство, являются залогом его высочайшей производительности на долгое время.'
    catalog.price=56900
    catalog.photo='images/product33.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 11
    sale.rating = 5
    sale.details='Меня все устроило. Выбирала по отзывам, цене и возможности использовать sim. Брала как резервный аппарат. Установила мессенджеры, YouTube, пару детских лёгких игр и приложения Юла и ВБ. На все встроенной памяти хватило, все тянет достаточно шустро.'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Планшет Samsung Galaxy Tab A8, 10.5", 64Gb, Wi-Fi+4G, Silver'
    catalog.details='Широкий 8.7-дюймовый дисплей для ярких впечатлений от фильмов и игр. Тонкая рамка позволила увеличить экран без изменения размеров планшета. Благодаря компактному эргономичному корпусу планшет очень удобно держать в руках, даже работая и играя часами.'
    catalog.price=66990
    catalog.photo='images/product34.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 14
    sale.rating = 5
    sale.details='Добротный, красивый, все пришло как надо, зарядник наш,не евровилка! Звук и яркость хорошие! Внешние качества супер! Экран большой, сам тонкий! Я довольна!'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####
    
    catalog = Catalog()
    catalog.category = category
    catalog.title='Планшет Samsung Galaxy Tab A8, 10.5", 64Gb, Wi-Fi+4G, Silver'
    catalog.details='Благодаря тонким рамкам (10.2 мм) планшета Galaxy Tab A8 вы сможете полностью погрузиться в происходящее на большом 10.5" экране. Наслаждайтесь любимыми фильмами и контентом вместе с Galaxy Tab A8, открывая для себя новый удивительный мир.'
    catalog.price=96990
    catalog.photo='images/product35.jpg'
    catalog.save()
    
    sale = Sale()
    #sale.saleday = datetime.now() 
    sale.catalog = catalog
    sale.price = catalog.price
    sale.quantity = 1
    sale.user_id = 21
    sale.rating = 5
    sale.details='Лёгкий, шустрый, большой'
    sale.save()
    sale.saleday = datetime.now() - timedelta(days=30)
    sale.save()

    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday 
    delivery.movement = 'Заявка принята в обработку'
    delivery.details='Заявка принята в обработку'
    delivery.save()
    delivery.deliveryday = sale.saleday
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заказ в пути'
    delivery.details='Заказ в пути'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=0.5)
    delivery.save()
    
    delivery = Delivery()
    delivery.sale = sale
    #delivery.deliveryday = sale.saleday
    delivery.movement = 'Заявка закрыта, заказ доставлен'
    delivery.details='Заявка закрыта, заказ доставлен'
    delivery.save()
    delivery.deliveryday = sale.saleday + timedelta(hours=1)
    delivery.save()

    #####

    print("Catalog Ok")

    ##### Новости #####
    News = apps.get_model("product", "News")
    
    news = News()
    news.daten = datetime.now() - timedelta(days=35)
    news.title = 'Смартфоны OnePlus'
    news.details = """С 2014 года компания OnePlus выпустила 8 революционных смартфонов в более чем 50 странах. Встречайте новую линейку смартфонов - «Nord», которая поступила в магазины
    """
    news.photo = 'images/news1.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=30)
    news.title = 'Помощь в выборе смартфонае'
    news.details =  """Более 300 моделей смартфонов в наличии! Как выбрать подходящий? Воспользоваться нашим smart-консультантом, ответив на вопросы которого, вы получите подборку идеальных смартфонов именно для вас! А оформить заказ на понравившийся можно в пару кликов.
    """
    news.photo = 'images/news2.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=25)
    news.title = 'Xiaomi 12 и Redmi Note 11 Pro'
    news.details = """Новинки Redmi Note 11 Pro и Xiaomi 12 поступили в продажу!
    """
    news.photo = 'images/news3.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=20)
    news.title = 'Поступление смартфонов Tecno'
    news.details = """Смартфоны Tehno поступили в магазины «Белый Ветер» и интернет-магазин shop.kz. Среди уже знакомых нам серий Spark, Pova, Camon и POP5 появились новые для нашего ассортимента модели – Spark GO 2022 и POP5 LTE.
    """
    news.photo = 'images/news4.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=15)
    news.title = 'Новинки Xiaomi 12 Lite и POCO C40'
    news.details = """Новинки смартфонов от Xiaomi и POCO уже в продаже!
    """
    news.photo = 'images/news5.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=10)
    news.title = 'Xiaomi Smart Band 7'
    news.details = """В продажу поступили фитнес-трекеры Xiaomi Smart Band 7! Новинка получила крайне широкие функциональные возможности, обновленный внешний вид, улучшенное программное обеспечение и привлекательный ценник.
    """
    news.photo = 'images/news6.jpeg' 
    news.save()
    
    news = News()
    news.daten = datetime.now() - timedelta(days=5)
    news.title = 'Повышенные бонусы за отзывы!'
    news.details = """Писать отзывы не только полезно, но и выгодно! Делитесь вашими впечатлениями о товарах на сайте и получайте повышенные бонусы!
    """
    news.photo = 'images/news7.jpeg' 
    news.save()
    
    print("News Ok")



class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),
        migrations.RunSQL("""CREATE VIEW view_catalog AS
                        SELECT catalog.id, catalog.category_id, category.title AS category, catalog.title, catalog.details, catalog.price, catalog.photo, 
                        (SELECT AVG(rating) FROM sale WHERE sale.catalog_id = catalog.id) AS avg_rating
                        FROM catalog LEFT JOIN category ON catalog.category_id = category.id;"""),
        migrations.RunSQL("""CREATE VIEW view_sale AS
                        SELECT sale.id, username, saleday, catalog_id, view_catalog.category, view_catalog. title, view_catalog.photo, sale.price, sale.quantity, sale.price*sale.quantity AS total, user_id, rating, sale.details,
                        (SELECT strftime('%d.%m.%Y',deliveryday) || ' - ' || movement FROM delivery WHERE sale_id = sale.id AND deliveryday = (SELECT MAX(deliveryday) AS Expr1 FROM delivery AS S WHERE  (sale_id = sale.id) )) AS final
                        FROM sale LEFT JOIN view_catalog ON sale.catalog_id = view_catalog.id
                        LEFT JOIN auth_user ON sale.user_id = auth_user.id"""),
    ]

